theme: jekyll-theme-slate
title: Do investments in Opportunity Zones benefit slow-growth areas?
description: Analysis of Census data and a small subset of available Opportunity Zones shows the answer might be no.
